### ISSUE TITLE
Runtime

### ISSUE THREAD

**Issue by Lionward** [holstegelab/treat#1]
I am running your tool now on HG002 Hifi BAM file from GIAB. on a ~900k regions from GIAB 
I am using 32 cores for the run.
In your pre-print you mentioned that it took around 45 minutes for CCS reads, if I understood correctly.
it's running now for more than 134 minutes...  so I was wondering if I did everything correctly.

<img width="1081" alt="grafik" src="https://github.com/holstegelab/treat/assets/33492430/a7409329-174a-4d5c-9de6-03343512c3a9">

thank you in advance.

**Comment by TesiNicco** [comment]
Hi Lionward, thanks for reaching. I see you are using the read-based analysis. For large datasets, we recommend using the assembly-based analysis at this moment.

Did you try using the assembly-based analysis? See below:
TREAT.py assembly -i bam_file -b bed_file -r reference_fasta -o output_directory

**Comment by Lionward** [comment]
thank you for the fast reply! 
I tried running the assembly analysis on 100 regions, I faced this error:

<img width="1199" alt="grafik" src="https://github.com/holstegelab/treat/assets/33492430/9d6ef322-9feb-4a55-9003-d945f9779654">

would appreciate the help.

Regards 

Lion

**Comment by TesiNicco** [comment]
Hi Lion,

could you share the regions you are analyzying? 
Then I can try to replicate your issue

Thanks

**Comment by Lionward** [comment]
chr1    16682   16774   TGGTGGGGG
chr1    19275   19473   TGAGAAGGCAGAGGCGCGACTGGGGTTCATGAGGAAAGGGAGGAGGAGGATGTGGGATGGTGGAGGGGTT
chr1    20798   20893   GAGCCACCACAGAAAACA
chr1    29714   29822   CCCCG
chr1    30824   30989   TC
chr1    31777   31847   AC
chr1    35458   35537   ATAA
chr1    44805   44906   AAAT
chr1    49795   49891   AAAAC
chr1    50451   50656   TTTCTTTCTCTCCTTTCCTTTCCTTGCA
chr1    52226   52333   TCTT
chr1    54682   54847   TTTC
chr1    62201   62319   CTTCATTTCAATT
chr1    66127   66662   TA
chr1    72059   72194   TATA
chr1    83475   83712   AAAGGCAACGCGTCATTTACAAAGGATCCTCAATAAGTTTGACAGCAGAGAGTGCATTATAAACCATGGATGCCAGAAGAGCTTAGGAA
chr1    83766   84081   AAAG
chr1    88644   88992   ACCCAGAGTGCTCGTGACGGCCAGCAGAGCCGGCCCCCATCTCCTCTGACCTCCCACCTCTCGCCCTCAGC
chr1    90017   90460   AACCTGCTGCTTCCTGGAGGAAGACAGTCCCTCAGTCCCTCTGTCTCTGCCAACCAGTT
chr1    90577   90666   CTGT

here you go

**Comment by Lionward** [comment]
I tried the same regions using the reads analysis and it worked .... just the assembly is not working.
And also is there an estimate for the runtime for reads analysis? 

Thank you!

**Comment by TesiNicco** [comment]
Hi Lion,

thanks for following up on this. We tried to replicate the issue, but we couldn't. We used the same input bam downloaded from [here](https://github.com/genome-in-a-bottle/giab_data_indexes/blob/master/AshkenazimTrio/alignment.index.AJtrio_PacBio_CCS_15kb_20kb_chemistry2_pbmm2_GRCh37_GRCh38_12162019.HG002), and the regions that you shared. The command we used was the following:

TREAT.py assembly -i HG002.SequelII.merged_15kb_20kb.pbmm2.GRCh38.haplotag.10x.bam -b regions.bed -r reference.fa -o output_folder 

A VCF file was correctly produced with no strange behaviors.

As using the reads analysis worked, this issue seems related to our assembler. Did you try an example run on the test data included in the repository? A simple test would be:
TREAT.py assembly -i test_data/example.bam -b test_data/example.bed -r reference_hg38.fa -o output_folder
If this is also not working, maybe the assembler ([otter](https://github.com/holstegelab/otter)) installation did not complete successfully, and you may want to double check that.

If you want to run the reads analysis on such large dataset of TRs, I would suggest running in batches of ~100k-200k TRs each. An estimate is about 1-1.5h for 200k TRs, although it depends on the genome coverage.

In the meanwhile, we are still trying to replicate this.

Please let us know how this evolves
Thanks

**Comment by ansalaza** [comment]
Just to comment, maybe there is indeed an installation issue with [otter](https://github.com/holstegelab/otter).
Just downloaded the HG002 BAM file and ~937k TRs file you are using and did an md5sum check.
Ran otter on it and haven't seen an issue so far; looks like it will take  ~3.5 hrs with 4 threads (assembly only) since its fairly high coverage (~50-70x). Will let you know when that finishes

**Comment by TesiNicco** [comment]
Hi Lion,

I will close this issue for now, but please don't hesitate to reach us for further comments, feedbacks, or bugs.

Thanks
